# Use the appropriate base image for Windows/amd64
FROM plugins/base:windows-ltsc2022-amd64

# Copy the binary from your release directory to the /bin/ directory in the image
ADD release/windows/amd64/drone-cobertura-s3.exe /bin/

# Set the entry point for the container
ENTRYPOINT ["C:\\\\bin\\drone-cobertura-s3.exe"]
