FROM arm64v8/alpine:3.15 as builder

RUN apk --no-cache add ca-certificates

FROM arm64v8/alpine:3.15

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENV GODEBUG netdns=go

COPY release/linux/arm64/drone-cobertura-s3 /bin/

ENTRYPOINT ["/bin/drone-cobertura-s3"]
